create table "ROOT".CLIENTE
(
	id INT not null primary key
        GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1),
	NOME VARCHAR(255),
	SOBRENOME VARCHAR(255),
	DATANASCIMENTO DATE,
	CPF VARCHAR(12),
	TELEFONE VARCHAR(14),
	SEXO VARCHAR(20)
);